### PR TITLE
Add tox-linters jobs to ansible-zuul-jobs

### PR DESCRIPTION
**Pull request by pabelanger**
This is the first step to start adding gating jobs to
ansible-zuul-jobs, this will be used to help increase code coverage
and prevent broken code from landing.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck (to test the new connection webhook url)

**Comment by TristanCacqueray** [comment]
recheck

**Comment by gundalow** [comment]
I've deleted call-ansible-test-sanity

recheck

**Comment by gundalow** [comment]
recheck

**Pull request merged**
